import: definition.yaml

concurrency:
  task:
    # dbbench-std: 5
    alfworld-quit-std: 1
    # alfworld-std: 1
    # os-std: 5
  agent:
    # gpt-3.5-turbo-0613: 5
    gpt-4o-mini: 1

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      # - gpt-3.5-turbo-0613
      - gpt-4o-mini
    task:
      # - dbbench-std
      # - os-std
      # - alfworld-std
      - alfworld-quit-std
output: "outputs/{TIMESTAMP}"
