default:
  module: src.server.tasks.alfworld_quit.ALFWorldQuit
  docker:
    image: longinyu/agentbench-alfworld
    command: umask 0; [ -f /root/.setup.sh ] && bash /root/.setup.sh;
  parameters:
    name: alfworld-quit-std
    data_path: "/AgentBench/data/alfworld"
    config_path: "src/server/tasks/alfworld/configs/base_config.yaml"
    prompts_path: "src/server/tasks/alfworld/prompts/alfworld_multiturn_plan_first.json"
    split: "standard"
    max_step: 35

alfworld-quit-dev:
  parameters:
    name: alfworld-quit-dev
    split: "dev"

alfworld-quit-std:
  parameters:
    name: alfworld-quit-std
    split: "standard"
